import { PlayCircle, PauseCircle, ShieldCheck } from 'lucide-react';
import type { PlatformTenant, PlatformUser } from '../types';
import { Empty, IconButton, Status } from '../components/ui';

export function TenantTable({tenants,currentTenantID,busy,onAction,compact=false}:{tenants:PlatformTenant[];currentTenantID:string;busy:string;onAction?:(tenant:PlatformTenant)=>void;compact?:boolean}) {return <div className="admin-table-scroll"><div className={`admin-tenant-table ${compact?'is-compact':''}`}><header><span>租户</span><span>状态</span><span>成员</span><span>项目</span><span>在线设备</span><span>活跃任务</span><span>最近活动</span>{!compact&&<span>操作</span>}</header>{tenants.length===0?<Empty title="没有匹配的租户"/>:tenants.map(tenant=><article key={tenant.id}><div className="admin-tenant-name"><span>{tenant.name.slice(0,1)}</span><div><strong>{tenant.name}</strong><small>{tenant.slug}</small></div></div><Status value={tenant.status}/><strong>{tenant.member_count}</strong><strong>{tenant.project_count}</strong><strong>{tenant.device_count}</strong><strong>{tenant.active_run_count}</strong><time>{tenant.last_activity_at?formatRelative(tenant.last_activity_at):'暂无活动'}</time>{!compact&&<div className="admin-row-action">{tenant.id===currentTenantID?<span>当前租户</span>:tenant.status==='active'?<IconButton label={`停用 ${tenant.name}`} disabled={busy===tenant.id} onClick={()=>onAction?.(tenant)}><PauseCircle size={17}/></IconButton>:<IconButton label={`恢复 ${tenant.name}`} disabled={busy===tenant.id} onClick={()=>onAction?.(tenant)}><PlayCircle size={17}/></IconButton>}</div>}</article>)}</div></div>}

export function UserAvatar({user}:{user:PlatformUser}) {return <span className="admin-user-avatar">{(user.display_name||user.email).slice(0,1).toUpperCase()}</span>}
export function AdminBadge({long=false}:{long?:boolean}) {return <span className="admin-badge"><ShieldCheck size={12}/>{long?'平台管理员':'管理员'}</span>}
export const roleLabel=(value:string)=>({tenant_admin:'租户管理员',project_manager:'项目经理',strategist:'策略',editor:'编辑',reviewer:'审核',viewer:'查看者'}[value]||value);
export const formatDate=(value:string)=>new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value));
function formatRelative(value:string){const seconds=Math.round((Date.now()-new Date(value).getTime())/1000);if(seconds<60)return '刚刚';if(seconds<3600)return `${Math.floor(seconds/60)} 分钟前`;if(seconds<86400)return `${Math.floor(seconds/3600)} 小时前`;return formatDate(value)}
