import { AlertCircle, ArrowRight, BookOpen, Check, CheckCircle2, ChevronRight, FileCheck2, FileInput, ListTodo, PackageCheck, Plus, Search, ShieldAlert, ShieldCheck, X, XCircle } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button, Empty, Field, IconButton, Modal } from '../../components/ui';
import type { EvidenceSpan, KnowledgeObject, KnowledgePack, KnowledgeQueryResult, KnowledgeSnapshot, Source, SourceRevision } from '../../types';
import { evidenceLocatorLabel, knowledgeBlockReasonLabel, knowledgeLayerLabel, knowledgeNextActionLabel, knowledgeObjectTypeLabel, knowledgeObjectTypeValue, knowledgePackPurposeLabel, sourceTypeLabel, statusLabel } from '../../uiLabels';
import { knowledgeApi, type GovernedKnowledgeObject } from './knowledgeApi';
import '../../styles/workSurface.css';

export interface KnowledgeProject {id:string;brand_name:string;product_name:string}
type KnowledgeTab='overview'|'objects'|'review'|'sources'|'packs'|'query';
type KnowledgeDecision='approve'|'reject';

const knowledgeStatusLabels:Record<string,string>={candidate:'待确认',needs_review:'待审核',pending:'待处理',verified:'已核验',approved:'已确认',valid:'有效',active:'生效中',blocked:'暂时无法使用',conflicted:'有冲突',prohibited:'已禁止',expired:'已过期',rejected:'已拒绝',superseded:'已替代',revoked:'已撤销',open:'待解决',source_missing:'缺少来源',collecting:'补充资料中',resolved:'已解决',waived:'已豁免',accepted_risk:'已接受风险',published:'已发布',draft:'草稿',retired:'已停用'};

export function knowledgeObjectAllows(value:{allowed_actions?:readonly string[]},action:KnowledgeDecision){return value.allowed_actions?.includes(action)??false}
function knowledgeObjectNeedsAttention(value:GovernedKnowledgeObject){return Boolean(value.allowed_actions?.length)||['evidence_required','requires_resolution'].includes(value.governance_state||'')}
function latestKnowledgeObjects<T extends KnowledgeObject>(values:T[]){const latest=new Map<string,T>();for(const value of values){const previous=latest.get(value.id);if(!previous||value.version>previous.version)latest.set(value.id,value)}return [...latest.values()].sort((left,right)=>left.title.localeCompare(right.title,'zh-CN'))}

export function GovernedKnowledgePage({projects,projectID,onProject}:{projects:KnowledgeProject[];projectID?:string;onProject?:(projectID:string)=>void}){
  const project=projects.find(item=>item.id===projectID)||projects[0];
  const navigate=useNavigate();
  const [tab,setTab]=useState<KnowledgeTab>('overview');
  const [objects,setObjects]=useState<GovernedKnowledgeObject[]>([]);
  const [packs,setPacks]=useState<KnowledgePack[]>([]);
  const [sources,setSources]=useState<Source[]>([]);
  const [selected,setSelected]=useState<GovernedKnowledgeObject>();
  const [query,setQuery]=useState('');
  const [notice,setNotice]=useState('');
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState('');
  const [actionError,setActionError]=useState('');

  useEffect(()=>{
    if(!project){setLoading(false);return}
    let active=true;
    setLoading(true);setError('');setSelected(undefined);
    Promise.all([knowledgeApi.objects(project.id),knowledgeApi.packs(project.id),knowledgeApi.sources(project.id)])
      .then(([nextObjects,nextPacks,nextSources])=>{if(active){setObjects(latestKnowledgeObjects(nextObjects));setPacks(nextPacks);setSources(nextSources)}})
      .catch(value=>{if(active)setError(value instanceof Error?value.message:'知识库加载失败')})
      .finally(()=>{if(active)setLoading(false)});
    return()=>{active=false};
  },[project?.id]);

  const filtered=objects.filter(item=>tab!=='review'||knowledgeObjectNeedsAttention(item)).filter(item=>query.trim()===''||`${item.title}${item.statement}${item.object_type}${item.layer}`.toLowerCase().includes(query.trim().toLowerCase()));
  const transition=async(decision:KnowledgeDecision,reason:string)=>{
    if(!selected||!project||!knowledgeObjectAllows(selected,decision))return;
    try{
      const result=await knowledgeApi.transition(selected.id,{expected_version:selected.version,expected_digest:selected.digest,decision,reason});
      setObjects(current=>latestKnowledgeObjects<GovernedKnowledgeObject>([...current,result.object]));
      setSelected(undefined);setNotice(decision==='approve'?'内容已确认，新的版本已经保存。':'这条内容已拒绝，审核记录已经保存。');setActionError('');
      try{setObjects(latestKnowledgeObjects(await knowledgeApi.objects(project.id)))}catch{setActionError('决定已经保存，但列表刷新失败；重新打开知识库即可恢复。')}
    }catch(value){setActionError(value instanceof Error?value.message:'内容处理失败')}
  };

  if(!project)return <div className="studio-view workos-page"><PageHeader eyebrow="客户创作台 / 知识库" title="知识库" description="请先选择一个项目。"/><Empty title="还没有项目" detail="项目创建后，资料来源、确认内容和已发布内容会在这里统一管理。"/></div>;
  if(loading)return <div className="studio-view workos-page knowledge-page"><PageHeader eyebrow={`项目 / ${project.brand_name} / 知识库`} title="知识库" description="正在读取资料和已确认内容。"/><div className="workos-loading">正在读取知识库…</div></div>;
  return <div className="studio-view workos-page knowledge-page">
    <PageHeader eyebrow={`项目 / ${project.brand_name} / 知识库`} title="知识库" description="在同一页面管理资料来源、参考依据和已确认内容。" actions={<>{projects.length>1&&onProject&&<label className="knowledge-project-select"><span>当前项目</span><select value={project.id} onChange={event=>onProject(event.target.value)}>{projects.map(item=><option key={item.id} value={item.id}>{item.brand_name} · {item.product_name}</option>)}</select></label>}<Button variant="secondary" onClick={()=>setTab('sources')}><FileInput size={15}/>添加资料来源</Button><Button onClick={()=>navigate(`/studio/tasks/new?project=${encodeURIComponent(project.id)}`)}><Plus size={15}/>补充内容</Button></>}/>
    {error&&<div className="workos-notice is-error"><AlertCircle size={16}/><span>{error}</span></div>}
    {actionError&&<div className="workos-notice is-error"><AlertCircle size={16}/><span>{actionError}</span><IconButton label="关闭错误" onClick={()=>setActionError('')}><X size={15}/></IconButton></div>}
    <section className="knowledge-summary"><KnowledgeMetric label="内容总数" value={String(objects.length)} detail="当前项目"/><KnowledgeMetric label="待处理" value={String(objects.filter(knowledgeObjectNeedsAttention).length)} detail="你可以处理" tone="warning"/><KnowledgeMetric label="有冲突" value={String(objects.filter(item=>item.status==='conflicted'||item.object_type==='ConflictRecord').length)} detail="解决后才能使用" tone="danger"/><KnowledgeMetric label="还缺少的内容" value={String(objects.filter(item=>item.object_type==='KnowledgeGap').length)} detail="可以创建补充任务" tone="info"/><KnowledgeMetric label="可用内容合集" value={String(packs.filter(pack=>pack.status==='published').length)} detail={`${sources.length} 个来源`} tone="success"/></section>
    {notice&&<div className="workos-notice is-success"><CheckCircle2 size={16}/><span>{notice}</span><IconButton label="关闭提示" onClick={()=>setNotice('')}><X size={15}/></IconButton></div>}
    <div className="knowledge-tabs">{([['overview','概览'],['objects','知识内容'],['review','待确认'],['sources','来源与依据'],['packs','可用内容合集'],['query','查找内容']] as const).map(([id,label])=><button key={id} className={tab===id?'is-active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
    {tab==='overview'?<KnowledgeOverview objects={objects} onTab={setTab} onSelect={setSelected}/>:tab==='sources'?<KnowledgeSources projectID={project.id} sources={sources} onCreated={async()=>{try{setSources(await knowledgeApi.sources(project.id));setNotice('来源已登记，正在整理原文依据。');setActionError('')}catch(value){setActionError(value instanceof Error?value.message:'来源列表刷新失败')}}}/>:tab==='packs'?<KnowledgePacks projectID={project.id} packs={packs} objects={objects} onChanged={async()=>setPacks(await knowledgeApi.packs(project.id))} onError={setActionError}/>:tab==='query'?<KnowledgeQuery projectID={project.id} packs={packs} query={query} setQuery={setQuery} onNotice={setNotice} onError={setActionError}/>:<KnowledgeObjectTable tab={tab} query={query} onQuery={setQuery} objects={filtered} onSelect={setSelected}/>}
    {selected&&<KnowledgeDrawer value={selected} onClose={()=>setSelected(undefined)} onDecision={transition} onTask={()=>{setSelected(undefined);navigate(`/studio/tasks/new?project=${encodeURIComponent(project.id)}`)}}/>}
  </div>;
}

function KnowledgeOverview({objects,onTab,onSelect}:{objects:GovernedKnowledgeObject[];onTab:(tab:KnowledgeTab)=>void;onSelect:(object:GovernedKnowledgeObject)=>void}){
  const layers=[['identity','品牌身份'],['product','产品信息'],['market','市场洞察'],['expression','内容表达'],['operations','业务运营'],['content_engine','内容方法'],['compliance','合规要求']];
  const stateFor=(layer:string)=>{const scoped=objects.filter(item=>item.layer===layer);if(scoped.length===0)return'未建立';if(scoped.some(item=>item.status==='conflicted'||item.object_type==='ConflictRecord'))return'有冲突';if(scoped.some(knowledgeObjectNeedsAttention))return'待处理';return'已准备'};
  const reviewObjects=objects.filter(knowledgeObjectNeedsAttention).slice(0,4);
  return <div className="knowledge-overview-grid"><section className="workos-section"><SectionHeader kicker="内容准备" title="知识内容准备情况"/><div className="coverage-list">{layers.map(([layer,label])=>{const state=stateFor(layer);return <button key={layer} onClick={()=>onTab('objects')}><span className="coverage-bar"><i className={state==='已准备'?'is-full':state==='有冲突'?'is-danger':'is-half'}/></span><strong>{label}</strong><small>{state}</small><ChevronRight size={14}/></button>})}</div></section><section className="workos-section"><SectionHeader kicker="待处理" title="需要你处理的内容" action={<button className="text-action" onClick={()=>onTab('review')}>查看待处理内容 <ArrowRight size={14}/></button>}/><div className="knowledge-review-list">{reviewObjects.length===0?<Empty title="没有待处理内容" detail="当前账号没有需要处理的知识内容。"/>:reviewObjects.map(item=><button key={`${item.id}:${item.version}`} onClick={()=>onSelect(item)}><span className="object-mark is-review"><BookOpen size={15}/></span><span><strong>{item.title}</strong><small>{knowledgeStatusLabels[item.status]||statusLabel(item.status)} · {item.impact||'需要确认来源'}</small></span><ChevronRight size={14}/></button>)}</div></section><section className="workos-section knowledge-query-card"><SectionHeader kicker="查找内容" title="查找前先选择范围"/><p>查找结果分为可以使用、暂时不能使用和还缺少的内容。查找不会修改知识内容，也不会把暂时不能使用的内容当作可用依据。</p><button className="text-action" onClick={()=>onTab('query')}>开始查找 <ArrowRight size={14}/></button></section></div>;
}

function KnowledgeObjectTable({tab,query,onQuery,objects,onSelect}:{tab:KnowledgeTab;query:string;onQuery:(value:string)=>void;objects:GovernedKnowledgeObject[];onSelect:(value:GovernedKnowledgeObject)=>void}){return <section className="workos-section knowledge-object-section"><div className="knowledge-toolbar"><label className="search-field"><Search size={16}/><input value={query} onChange={event=>onQuery(event.target.value)} placeholder="搜索知识内容、说明或类型" aria-label="搜索知识内容"/></label><span>{objects.length} 条内容</span></div><div className="knowledge-object-table"><div className="knowledge-table-head"><span>内容</span><span>分类 / 类型</span><span>状态</span><span>来源</span><span>影响</span><span/></div>{objects.length===0?<Empty title={tab==='review'?'没有待处理内容':'还没有知识内容'} detail={tab==='review'?'当前账号没有需要处理的内容。':'从项目资料中提交内容并完成来源确认后，会显示在这里。'}/>:objects.map(item=><button className="knowledge-object-row" key={`${item.id}:${item.version}`} onClick={()=>onSelect(item)}><div><strong>{item.title}</strong><small><code>{item.id}</code> · v{item.version}</small></div><div><span className="layer-label">{knowledgeLayerLabel(item.layer)}</span><small>{knowledgeObjectTypeLabel(item.object_type)}</small></div><StatusText value={item.status}/><div className="evidence-count"><FileCheck2 size={14}/>{item.evidence_refs.length?`${item.evidence_refs.length} 条来源`:'缺少来源'}</div><small>{item.impact||'未标记'}</small><ChevronRight size={15}/></button>)}</div></section>}

function KnowledgeSources({projectID,sources,onCreated}:{projectID:string;sources:Source[];onCreated:()=>Promise<void>}){
  const [name,setName]=useState('');const [file,setFile]=useState<File>();const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [selectedID,setSelectedID]=useState('');const [revisionFile,setRevisionFile]=useState<File>();const [revisions,setRevisions]=useState<SourceRevision[]>([]);const [evidence,setEvidence]=useState<EvidenceSpan[]>([]);const selected=sources.find(source=>source.id===selectedID);
  useEffect(()=>{if(!selected){setRevisions([]);setEvidence([]);return}let active=true;knowledgeApi.sourceRevisions(selected.id).then(next=>{if(!active)return[];setRevisions(next);return next[0]?knowledgeApi.evidence(next[0].id):[]}).then(next=>{if(active)setEvidence(next)}).catch(()=>{if(active){setRevisions([]);setEvidence([])}});return()=>{active=false}},[selected?.id]);
  const create=async()=>{if(!name.trim()||!file){setNotice('请填写来源名称并选择文件。');return}setBusy(true);setNotice('');try{const form=new FormData();form.append('file',file);form.append('name',name.trim());form.append('source_type','local_import');await knowledgeApi.uploadSource(projectID,form);setName('');setFile(undefined);await onCreated();setNotice('资料已上传，系统正在整理内容。')}catch(value){setNotice(value instanceof Error?value.message:'资料上传失败')}finally{setBusy(false)}};
  const revise=async()=>{if(!selected||!revisionFile){setNotice('请选择要追加到当前来源的文件。');return}setBusy(true);setNotice('');try{const form=new FormData();form.append('file',revisionFile);await knowledgeApi.uploadSourceRevision(selected.id,form);setRevisionFile(undefined);setNotice('资料新版本已上传，旧的参考依据会保留并等待重新整理。');setRevisions(await knowledgeApi.sourceRevisions(selected.id))}catch(value){setNotice(value instanceof Error?value.message:'资料新版本上传失败')}finally{setBusy(false)}};
  return <div className="knowledge-subview-grid"><section className="workos-section knowledge-subview"><SectionHeader kicker="来源与依据" title="登记资料并查看原文依据" action={<span className="section-count">{sources.length} 个来源</span>}/><div className="source-create-form"><Field label="来源名称"><input value={name} onChange={event=>setName(event.target.value)} placeholder="例如：品牌创作简报 / 本地会话摘录"/></Field><Field label="本地文件"><input type="file" accept=".pdf,.docx,.xlsx,.pptx,.png,.jpg,.jpeg,.txt" onChange={event=>setFile(event.target.files?.[0])}/></Field><Button onClick={create} disabled={busy||!name.trim()||!file}><Plus size={15}/>{busy?'上传中…':'上传资料'}</Button></div>{notice&&<div className="workos-notice is-info">{notice}</div>}<div className="source-list">{sources.length===0?<Empty title="暂无已登记来源" detail="上传本地文件后，系统会保存内容摘要并整理出可核对的原文片段。"/>:sources.map(source=><button className={`source-row ${source.id===selectedID?'is-selected':''}`} key={source.id} onClick={()=>setSelectedID(source.id)}><span className="object-mark is-source"><FileInput size={15}/></span><span><strong>{source.name}</strong><small>{sourceTypeLabel(source.source_type)} · {source.revision_count} 个版本 · {statusLabel(source.status)}</small></span><ChevronRight size={15}/></button>)}</div></section><section className="workos-section knowledge-subview"><SectionHeader kicker="原文依据" title={selected?selected.name:'选择一个来源'}/>{!selected?<Empty title="还没有选择来源" detail="选择左侧来源，查看文件版本、整理状态和可核对的原文片段。"/>:<><div className="source-detail-facts"><span>最新版本 <b>{revisions[0]?.file_name||'未上传'}</b></span><span>整理状态 <b>{statusLabel(revisions[0]?.processing_status||selected.status)}</b></span><span>原文片段 <b>{evidence.length}</b></span></div><div className="source-revision-upload"><input type="file" accept=".pdf,.docx,.xlsx,.pptx,.png,.jpg,.jpeg,.txt" onChange={event=>setRevisionFile(event.target.files?.[0])}/><Button variant="secondary" onClick={revise} disabled={busy||!revisionFile}><FileInput size={15}/>上传新版本</Button></div><div className="evidence-list">{evidence.length===0?<Empty title="尚无原文片段" detail="内容整理完成后，原文位置、引用文字和确认状态会保留在这里。"/>:evidence.map(item=><div className="evidence-row" key={item.id}><span className="object-mark is-source"><FileCheck2 size={15}/></span><div><strong>{item.quote_text}</strong><small>{evidenceLocatorLabel(item.locator_kind)} · {statusLabel(item.review_status)}</small></div><StatusText value={item.review_status}/><ChevronRight size={14}/></div>)}</div></>}</section></div>;
}

function KnowledgePacks({projectID,packs,objects,onChanged,onError}:{projectID:string;packs:KnowledgePack[];objects:KnowledgeObject[];onChanged:()=>Promise<void>;onError:(value:string)=>void}){
  const [name,setName]=useState('内容生产资料集');const [purpose,setPurpose]=useState('内容生产');const [busy,setBusy]=useState(false);const [snapshots,setSnapshots]=useState<Record<string,KnowledgeSnapshot[]>>({});const eligible=objects.filter(object=>['approved','verified','valid','active'].includes(object.status));
  useEffect(()=>{let active=true;setSnapshots({});packs.filter(pack=>pack.status==='published').forEach(pack=>knowledgeApi.snapshots(projectID,pack.id).then(next=>{if(active)setSnapshots(current=>({...current,[pack.id]:next}))}).catch(value=>{if(active)onError(value instanceof Error?value.message:'已发布版本读取失败')}));return()=>{active=false}},[packs,projectID]);
  const create=async()=>{if(!name.trim()||eligible.length===0)return;setBusy(true);try{await knowledgeApi.createPack(projectID,{name:name.trim(),purpose,object_refs:eligible.map(object=>({object_id:object.id,version:object.version})),query_policy:{eligible_statuses:['approved','verified','valid','active'],allowed_object_types:[],require_evidence:true,block_on_conflict:true,block_on_rights_failure:true}});await onChanged();onError('')}catch(value){onError(value instanceof Error?value.message:'内容合集创建失败')}finally{setBusy(false)}};
  const publish=async(packID:string)=>{setBusy(true);try{await knowledgeApi.publishPack(packID);await onChanged();onError('')}catch(value){onError(value instanceof Error?value.message:'内容合集发布失败')}finally{setBusy(false)}};
  return <div className="knowledge-subview-grid"><section className="workos-section"><SectionHeader kicker="可用内容合集" title="按用途整理可使用的内容" action={<span className="section-count">{packs.length} 个合集</span>}/><div className="pack-create-form"><Field label="名称"><input value={name} onChange={event=>setName(event.target.value)}/></Field><Field label="用途"><input value={purpose} onChange={event=>setPurpose(event.target.value)}/></Field><span className="pack-selection-note">将收录 {eligible.length} 条已核验内容</span><Button onClick={create} disabled={busy||eligible.length===0}><Plus size={15}/>创建草稿</Button></div><div className="pack-list">{packs.length===0?<Empty title="还没有可用内容合集" detail="先完成知识内容审核，再按业务用途整理一份可以使用的内容合集。"/>:packs.map(pack=><article key={pack.id}><div><strong>{pack.name}</strong><span>{knowledgePackPurposeLabel(pack.purpose)} · {pack.object_refs.length} 条内容 · v{pack.version}</span></div><StatusText value={pack.status}/>{pack.status==='draft'&&<Button variant="secondary" disabled={busy} onClick={()=>publish(pack.id)}><PackageCheck size={14}/>发布</Button>}<ChevronRight size={15}/></article>)}</div></section><section className="workos-section"><SectionHeader kicker="固定版本" title="发布后会生成一份固定版本"/><div className="snapshot-list">{Object.keys(snapshots).length===0?<Empty title="还没有固定版本" detail="发布内容合集后，系统会生成一份固定版本，供任务使用。"/>:Object.entries(snapshots).flatMap(([packID,values])=>values.map(snapshot=><article className="snapshot-row" key={snapshot.id}><div><strong>{snapshot.id.slice(0,14)}…</strong><span>内容合集 {packID.slice(0,14)}… · {snapshot.objects.length} 条内容</span></div><code>{snapshot.digest.slice(0,18)}…</code></article>))}</div></section></div>;
}

function KnowledgeQuery({projectID,packs,query,setQuery,onNotice,onError}:{projectID:string;packs:KnowledgePack[];query:string;setQuery:(value:string)=>void;onNotice:(value:string)=>void;onError:(value:string)=>void}){
  const publishedPacks=useMemo(()=>packs.filter(pack=>pack.status==='published'),[packs]);const [packID,setPackID]=useState('');const [channel,setChannel]=useState('short_video');const [result,setResult]=useState<KnowledgeQueryResult>();const [busy,setBusy]=useState(false);
  useEffect(()=>{if(publishedPacks.length===0){setPackID('');setResult(undefined);return}if(!publishedPacks.some(pack=>pack.id===packID))setPackID(publishedPacks[0].id)},[packID,publishedPacks]);
  const run=async()=>{if(!packID)return;const objectTypes=query.split(/[\n,，]/).map(knowledgeObjectTypeValue).filter(Boolean);setBusy(true);onError('');try{const value=await knowledgeApi.query({project_id:projectID,pack_id:packID,channel,object_types:objectTypes,at:new Date().toISOString()});setResult(value);onNotice(`查找完成：${value.eligible.length} 条可用内容，${value.blocked.length} 条暂时不能使用，${value.gaps.length} 条还缺少内容。`)}catch(value){onError(value instanceof Error?value.message:'内容查找失败')}finally{setBusy(false)}};
  if(publishedPacks.length===0)return <div className="query-empty"><BookOpen size={22}/><strong>先准备一份可用内容合集</strong><span>查找只读取固定版本，不直接读取待确认内容。</span></div>;
  return <div className="knowledge-query-layout"><section className="workos-section"><SectionHeader kicker="查询范围" title="从可用内容合集中查找"/><Field label="内容合集"><select value={packID} onChange={event=>{setPackID(event.target.value);setResult(undefined)}}>{publishedPacks.map(pack=><option key={pack.id} value={pack.id}>{pack.name} · v{pack.version}</option>)}</select></Field><Field label="渠道"><select value={channel} onChange={event=>setChannel(event.target.value)}><option value="short_video">短视频</option><option value="wechat_article">公众号文章</option><option value="">不限制渠道</option></select></Field><Field label="内容类型（可选）"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="例如：营销主张、品牌规则"/><small className="field-hint">多个类型用逗号分隔；留空表示查询整个内容合集。</small></Field><Button onClick={run} disabled={busy||!packID}><Search size={15}/>{busy?'查询中…':'开始查询'}</Button></section><section className="workos-section query-result"><SectionHeader kicker="查询结果" title={result?'内容是否可用':'尚未运行查询'} action={result?<span className="query-digest">本次查询记录：{result.query_digest}</span>:undefined}/>{!result?<div className="query-empty"><Search size={22}/><strong>选择范围后开始查询</strong><span>结果只来自可用内容合集，查询本身不会改变任何内容。</span></div>:<><QueryResultRow label="可用" value={String(result.eligible.length)} detail="来源清楚、没有冲突，也满足使用条件" tone="is-success"/><QueryResultRow label="暂时不能使用" value={String(result.blocked.length)} detail="存在问题，不能直接作为内容依据" tone="is-danger"/><QueryResultRow label="还缺少内容" value={String(result.gaps.length)} detail="需要补充资料或创建新的内容任务" tone="is-warning"/>{result.blocked.length>0&&<div className="query-detail-list">{result.blocked.slice(0,5).map(item=><div key={item.object_id}><strong>{item.object_id}</strong><span>{item.reasons?.map(knowledgeBlockReasonLabel).join('、')||'还有条件未满足'}</span></div>)}</div>}{result.gaps.length>0&&<div className="query-detail-list">{result.gaps.slice(0,5).map(item=><div key={item.object_id}><strong>{item.object_id}</strong><span>{knowledgeNextActionLabel(item.next_action)}</span></div>)}</div>}<button className="text-action" onClick={()=>setResult(undefined)}>清除本次结果 <X size={14}/></button></>}</section></div>;
}

function KnowledgeDrawer({value,onClose,onDecision,onTask}:{value:GovernedKnowledgeObject;onClose:()=>void;onDecision:(decision:KnowledgeDecision,reason:string)=>Promise<void>;onTask:()=>void}){const [reason,setReason]=useState('');const [busy,setBusy]=useState<KnowledgeDecision>();const canApprove=knowledgeObjectAllows(value,'approve');const canReject=knowledgeObjectAllows(value,'reject');const canReview=canApprove||canReject;const decide=async(decision:KnowledgeDecision)=>{if(!reason.trim()||!knowledgeObjectAllows(value,decision))return;setBusy(decision);try{await onDecision(decision,reason.trim())}finally{setBusy(undefined)}};const taskLabel=value.governance_state==='governed'?'创建更新任务':value.governance_state==='requires_resolution'?'创建处理任务':'创建补充任务';return <Modal title="知识内容" onClose={onClose}><div className="knowledge-drawer-content"><div className="drawer-object-heading"><span className="object-mark is-knowledge"><BookOpen size={16}/></span><div><strong>{value.title}</strong><span><code>{value.id}</code> · v{value.version}</span></div><StatusText value={value.status}/></div><dl className="object-facts"><div><dt>内容类型</dt><dd>{knowledgeObjectTypeLabel(value.object_type)}</dd></div><div><dt>内容分类</dt><dd>{knowledgeLayerLabel(value.layer)}</dd></div><div><dt>原文依据</dt><dd>{value.evidence_refs.length?value.evidence_refs.join('、'):'缺少来源'}</dd></div><div><dt>影响</dt><dd>{value.impact||'未标记'}</dd></div></dl><section className="drawer-copy"><span>内容说明</span><p>{value.statement}</p></section><div className={`knowledge-governance-state is-${value.governance_state||'read_only'}`}>{value.governance_state==='governed'?<ShieldCheck size={17}/>:<ShieldAlert size={17}/>}<div><strong>{value.governance_state==='governed'?'已确认可使用':canReview?'需要你确认':'当前版本只读'}</strong><p>{value.governance_message||'当前没有可执行的审核动作，此版本仅供查看。'}</p></div></div>{canReview&&<Field label="审核说明" hint="审核说明会被保留，并生成新的内容版本。"><textarea rows={3} value={reason} onChange={event=>setReason(event.target.value)} placeholder="说明来源核验结果或拒绝原因"/></Field>}<div className="modal-actions"><Button variant="secondary" disabled={Boolean(busy)} onClick={onTask}><ListTodo size={15}/>{taskLabel}</Button>{canReject&&<Button variant="danger" disabled={Boolean(busy)||!reason.trim()} onClick={()=>void decide('reject')}><XCircle size={15}/>{busy==='reject'?'拒绝中…':'拒绝这条内容'}</Button>}{canApprove&&<Button disabled={Boolean(busy)||!reason.trim()} onClick={()=>void decide('approve')}><Check size={15}/>{busy==='approve'?'确认中…':'确认并保存'}</Button>}</div></div></Modal>}
function PageHeader({eyebrow,title,description,actions}:{eyebrow:string;title:string;description:string;actions?:React.ReactNode}){return <header className="workos-page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{actions&&<div className="workos-header-actions">{actions}</div>}</header>}
function SectionHeader({kicker,title,action}:{kicker:string;title:string;action?:React.ReactNode}){return <header className="workos-section-header"><div><span>{kicker}</span><h2>{title}</h2></div>{action}</header>}
function KnowledgeMetric({label,value,detail,tone='default'}:{label:string;value:string;detail:string;tone?:string}){return <article className={`knowledge-metric is-${tone}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>}
function StatusText({value}:{value:string}){return <span className={`status-text ${statusTone(value)}`}><i/>{knowledgeStatusLabels[value]||statusLabel(value)}</span>}
function statusTone(value:string){if(['approved','verified','valid','active','resolved','published'].includes(value))return'is-success';if(['blocked','conflicted','prohibited','expired','rejected','revoked'].includes(value))return'is-danger';if(['needs_review','candidate','pending','open','source_missing','collecting'].includes(value))return'is-warning';return'is-muted'}
function QueryResultRow({label,value,detail,tone}:{label:string;value:string;detail:string;tone:string}){return <div className="query-result-row"><span className={tone}><i/>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
