import { Check, FileKey2, Image, Plus, ShieldAlert, ShieldCheck, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { api, post } from '../api';
import { Banner, Button, Empty, Field, Modal, Status } from '../components/ui';
import type { Asset, Project, RightsRecord, Source } from '../types';
import { ProjectPage } from './OverviewView';

export function AssetRightsView({project}:{project:Project}) {
  const [assets,setAssets]=useState<Asset[]>([]);const [sources,setSources]=useState<Source[]>([]);const [selected,setSelected]=useState<Asset>();const [rights,setRights]=useState<RightsRecord[]>([]);const [show,setShow]=useState<'asset'|'rights'>();const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [error,setError]=useState('');
  const readySources=useMemo(()=>sources.filter(source=>source.status==='ready'&&source.latest_revision_id),[sources]);
  const load=()=>{setLoading(true);setError('');return Promise.all([api<Asset[]>(`/api/bff/projects/${project.id}/assets`),api<Source[]>(`/api/bff/projects/${project.id}/sources`)]).then(([assetItems,sourceItems])=>{setAssets(assetItems);setSources(sourceItems);setSelected(previous=>assetItems.find(item=>item.id===previous?.id)||assetItems[0])}).catch(e=>setError(e instanceof Error?e.message:'素材权利加载失败')).finally(()=>setLoading(false))};
  useEffect(()=>{load()},[project.id]);
  const loadRights=(assetID:string)=>api<RightsRecord[]>(`/api/bff/assets/${assetID}/rights`).then(setRights).catch(e=>{setRights([]);setError(e instanceof Error?e.message:'权利记录加载失败')});
  useEffect(()=>{if(selected)loadRights(selected.id);else setRights([])},[selected?.id]);
  const review=async(id:string,decision:'approve'|'reject')=>{setBusy(id);setError('');try{await post(`/api/bff/rights/${id}/review`,{decision});if(selected)await loadRights(selected.id);await load()}catch(e){setError(e instanceof Error?e.message:'审核失败')}finally{setBusy('')}};
  return <ProjectPage project={project} kicker="素材治理" title="素材与权利" actions={<Button onClick={()=>setShow('asset')}><Plus size={16}/>登记素材</Button>}>
    {error&&<Banner kind="error" onClose={()=>setError('')}>{error}</Banner>}
    <div className="rights-workspace"><section className="section rights-assets"><header className="section-header"><div><span className="section-kicker">生成输入</span><h2>{loading?'加载中':`${assets.length} 个素材`}</h2></div></header>{!loading&&assets.length===0?<Empty title="暂无治理素材" detail="先把就绪来源登记为素材，再补齐权利记录" action={<Button onClick={()=>setShow('asset')}>登记第一个素材</Button>}/>:assets.map(asset=><button key={asset.id} className={`rights-asset-row ${selected?.id===asset.id?'active':''}`} onClick={()=>setSelected(asset)}><span className="rights-asset-icon"><Image size={16}/></span><span><strong>{asset.name}</strong><small>{assetTypeLabel(asset.asset_type)} · {usageLabel(asset.usage_mode)}</small></span><Status value={asset.status}/></button>)}</section>
      <section className="section rights-detail"><header className="section-header"><div><span className="section-kicker">使用许可</span><h2>{selected?.name||'选择素材'}</h2></div>{selected&&<Button variant="secondary" onClick={()=>setShow('rights')}><FileKey2 size={15}/>新增权利</Button>}</header>{selected&&<div className={`rights-gate ${selected.status==='approved'&&selected.usage_mode!=='analysis_only'?'rights-gate-pass':'rights-gate-blocked'}`}>{selected.status==='approved'&&selected.usage_mode!=='analysis_only'?<ShieldCheck size={18}/>:<ShieldAlert size={18}/>}<div><strong>{selected.status==='approved'&&selected.usage_mode!=='analysis_only'?'可按有效权利进入 Task Contract':'当前不会进入 Task Contract'}</strong><span>{selected.usage_mode==='analysis_only'?'该素材被限定为只做结构分析':selected.status!=='approved'?'需要至少一条已批准且适用的权利记录':'服务端还会实时检查渠道、地域和期限'}</span></div></div>}{rights.length===0?<Empty title={selected?'尚无权利记录':'选择一个素材'} detail={selected?'权利主体、地域、渠道、期限和证明缺一不可':''}/>:<div className="rights-list">{rights.map(record=><article key={record.id}><header><div><strong>{record.rights_holder}</strong><span>{rightsTypeLabel(record.rights_type)}</span></div><Status value={record.status}/></header><dl><div><dt>地域</dt><dd>{record.territories.join('、')}</dd></div><div><dt>渠道</dt><dd>{record.channels.join('、')}</dd></div><div><dt>有效期</dt><dd>{periodLabel(record)}</dd></div><div><dt>证明</dt><dd>{record.proof_source_revision_id.slice(0,8)}</dd></div></dl>{record.restrictions.length>0&&<p>{record.restrictions.join('；')}</p>}{record.status==='needs_review'&&<footer><button title="批准权利" disabled={busy===record.id} onClick={()=>review(record.id,'approve')}><Check size={15}/></button><button title="拒绝权利" disabled={busy===record.id} onClick={()=>review(record.id,'reject')}><X size={15}/></button></footer>}</article>)}</div>}</section></div>
    {show==='asset'&&<CreateAssetModal project={project} sources={readySources} onClose={()=>setShow(undefined)} onCreated={()=>{setShow(undefined);load()}}/>}
    {show==='rights'&&selected&&<CreateRightsModal project={project} asset={selected} sources={readySources} onClose={()=>setShow(undefined)} onCreated={()=>{setShow(undefined);loadRights(selected.id);load()}}/>}
  </ProjectPage>
}

function CreateAssetModal({project,sources,onClose,onCreated}:{project:Project;sources:Source[];onClose:()=>void;onCreated:()=>void}) {
  const [form,setForm]=useState({name:'',asset_type:'product_image',source_revision_id:sources[0]?.latest_revision_id||'',usage_mode:'analysis_only'});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const set=(key:string,value:string)=>setForm(previous=>({...previous,[key]:value}));
  const submit=async()=>{setBusy(true);setError('');try{await post(`/api/bff/projects/${project.id}/assets`,form);onCreated()}catch(e){setError(e instanceof Error?e.message:'素材登记失败')}finally{setBusy(false)}};
  return <Modal title="登记治理素材" onClose={onClose}><div className="form-grid"><Field label="素材名称"><input value={form.name} onChange={e=>set('name',e.target.value)}/></Field><Field label="素材类型"><select value={form.asset_type} onChange={e=>set('asset_type',e.target.value)}><option value="product_image">产品图</option><option value="brand_mark">品牌标识</option><option value="packaging">包装</option><option value="person">人物肖像</option><option value="location">场地</option><option value="audio">音频</option><option value="other">其他</option></select></Field><Field label="不可变原件"><select value={form.source_revision_id} onChange={e=>set('source_revision_id',e.target.value)}>{sources.map(source=><option value={source.latest_revision_id} key={source.id}>{source.name}</option>)}</select></Field><Field label="使用模式"><select value={form.usage_mode} onChange={e=>set('usage_mode',e.target.value)}><option value="analysis_only">仅结构分析</option><option value="generation_reference">可生成参考</option><option value="owned">自有素材</option></select></Field>{sources.length===0&&<div className="form-hint"><Banner kind="warning">没有就绪来源，请先到“资料”上传并完成解析。</Banner></div>}</div>{error&&<p className="form-error">{error}</p>}<footer className="modal-actions"><Button variant="secondary" onClick={onClose}>取消</Button><Button disabled={busy||!form.name||!form.source_revision_id} onClick={submit}>{busy?'保存中…':'登记待审素材'}</Button></footer></Modal>
}

function CreateRightsModal({project,asset,sources,onClose,onCreated}:{project:Project;asset:Asset;sources:Source[];onClose:()=>void;onCreated:()=>void}) {
  const [form,setForm]=useState({rights_holder:project.brand_name,rights_type:'owned',territories:'CN',channels:project.channel,valid_from:'',valid_until:'',proof_source_revision_id:sources[0]?.latest_revision_id||'',restrictions:''});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const set=(key:string,value:string)=>setForm(previous=>({...previous,[key]:value}));
  const submit=async()=>{setBusy(true);setError('');try{await post(`/api/bff/assets/${asset.id}/rights`,{...form,territories:split(form.territories),channels:split(form.channels),restrictions:split(form.restrictions),valid_from:form.valid_from?new Date(form.valid_from).toISOString():null,valid_until:form.valid_until?new Date(form.valid_until).toISOString():null});onCreated()}catch(e){setError(e instanceof Error?e.message:'权利记录保存失败')}finally{setBusy(false)}};
  return <Modal title="新增权利记录" onClose={onClose}><div className="form-grid"><Field label="权利主体"><input value={form.rights_holder} onChange={e=>set('rights_holder',e.target.value)}/></Field><Field label="权利类型"><select value={form.rights_type} onChange={e=>set('rights_type',e.target.value)}><option value="owned">自有</option><option value="licensed_generation">生成授权</option><option value="licensed_edit">编辑授权</option><option value="public_domain">公有领域</option></select></Field><Field label="地域"><input value={form.territories} onChange={e=>set('territories',e.target.value)} placeholder="CN，多个用逗号分隔"/></Field><Field label="渠道"><input value={form.channels} onChange={e=>set('channels',e.target.value)} placeholder="douyin，多个用逗号分隔"/></Field><Field label="生效时间"><input type="datetime-local" value={form.valid_from} onChange={e=>set('valid_from',e.target.value)}/></Field><Field label="失效时间"><input type="datetime-local" value={form.valid_until} onChange={e=>set('valid_until',e.target.value)}/></Field><Field label="权利证明来源"><select value={form.proof_source_revision_id} onChange={e=>set('proof_source_revision_id',e.target.value)}>{sources.map(source=><option value={source.latest_revision_id} key={source.id}>{source.name}</option>)}</select></Field><Field label="使用限制"><textarea rows={3} value={form.restrictions} onChange={e=>set('restrictions',e.target.value)} placeholder="多个限制用换行分隔"/></Field></div>{error&&<p className="form-error">{error}</p>}<footer className="modal-actions"><Button variant="secondary" onClick={onClose}>取消</Button><Button disabled={busy||!form.rights_holder||!form.channels||!form.proof_source_revision_id} onClick={submit}>{busy?'保存中…':'提交权利审核'}</Button></footer></Modal>
}

function split(value:string){return value.split(/[，,\n]/).map(item=>item.trim()).filter(Boolean)}
function assetTypeLabel(value:string){return ({product_image:'产品图',brand_mark:'品牌标识',packaging:'包装',person:'人物',location:'场地',audio:'音频',other:'其他'} as Record<string,string>)[value]||value}
function usageLabel(value:string){return ({analysis_only:'仅分析',generation_reference:'生成参考',owned:'自有'} as Record<string,string>)[value]||value}
function rightsTypeLabel(value:string){return ({owned:'自有权利',licensed_generation:'生成授权',licensed_edit:'编辑授权',public_domain:'公有领域'} as Record<string,string>)[value]||value}
function periodLabel(record:RightsRecord){if(!record.valid_from&&!record.valid_until)return'长期';const start=record.valid_from?new Date(record.valid_from).toLocaleDateString('zh-CN'):'即日起';const end=record.valid_until?new Date(record.valid_until).toLocaleDateString('zh-CN'):'长期';return `${start} 至 ${end}`}
