import { ArrowRight, CheckCircle2, Clock3, FolderKanban, Laptop2, ShieldAlert, Sparkles } from 'lucide-react';
import type { Dashboard, Project } from '../types';
import { Empty, Status } from '../components/ui';

export function DashboardView({data,canManage,onProject,onCreate}:{data:Dashboard;canManage:boolean;onProject:(project:Project)=>void;onCreate:()=>void}) {
  const stats=[{label:'活跃项目',value:data.counts.projects||0,icon:FolderKanban,tone:'ink'},{label:'在线运行时',value:data.counts.devices||0,icon:Laptop2,tone:'green'},{label:'已批准知识',value:data.counts.knowledge_ready||0,icon:CheckCircle2,tone:'cyan'},{label:'待处理阻断',value:data.counts.open_blockers||0,icon:ShieldAlert,tone:'amber'}];
  return <div className="page"><div className="page-heading"><div><span className="eyebrow">运营工作台</span><h1>{data.tenant.name}</h1><p>项目、知识、内容与审批</p></div>{canManage&&<button className="button button-primary" onClick={onCreate}>新建项目</button>}</div>
    <section className="stat-grid">{stats.map(({label,value,icon:Icon,tone})=><div className="stat" key={label}><div className={`stat-icon tone-${tone}`}><Icon size={19}/></div><div><strong>{value}</strong><span>{label}</span></div></div>)}</section>
    <section className="pipeline-band"><header><div><span className="section-kicker">生产管线</span><h2>从资料到客户批准</h2></div><span className="updated"><Clock3 size={15}/> 实时状态</span></header><div className="pipeline">{data.pipeline.map((stage,index)=><div className="pipeline-stage" key={stage.id}><div className="pipeline-value">{stage.count}</div><strong>{stage.label}</strong>{stage.blocked>0?<span className="pipeline-blocked">{stage.blocked} 个阻断</span>:<span>状态正常</span>}{index<data.pipeline.length-1&&<ArrowRight className="pipeline-arrow" size={17}/>}</div>)}</div></section>
    <div className="dashboard-columns"><section className="section"><header className="section-header"><div><span className="section-kicker">项目</span><h2>最近更新</h2></div></header>{data.projects.length===0?<Empty title="还没有项目" action={canManage?<button className="button button-primary" onClick={onCreate}>创建项目</button>:undefined}/>:<div className="project-list">{data.projects.map(project=><button key={project.id} className="project-row" onClick={()=>onProject(project)}><div className="project-glyph">{project.brand_name.slice(0,1)}</div><div className="project-main"><strong>{project.brand_name}</strong><span>{project.product_name}</span></div><Status value={project.status}/><div className="project-metric"><strong>{project.knowledge_ready}</strong><span>知识</span></div><div className="project-metric"><strong>{project.connected_devices}</strong><span>设备</span></div><ArrowRight size={17}/></button>)}</div>}</section>
      <section className="section"><header className="section-header"><div><span className="section-kicker">任务</span><h2>本地创作运行</h2></div></header>{data.recent_runs.length===0?<Empty title="暂无运行记录"/>:<div className="run-list">{data.recent_runs.map(run=><div className="run-row" key={run.id}><div className="run-icon"><Sparkles size={17}/></div><div><strong>{runLabel(run.task_type)}</strong><span>{shortID(run.id)} · {formatTime(run.created_at)}</span></div><Status value={run.state}/></div>)}</div>}</section></div>
  </div>
}
const shortID=(id:string)=>id.slice(0,8);
const runLabel=(taskType:string)=>taskType==='knowledge_extract'?'品牌知识提取':taskType.replaceAll('_',' ');
const formatTime=(value:string)=>new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value));
