import { Archive, Check, Clipboard, Laptop2, LoaderCircle, Pencil, Plus, RotateCcw, ShieldCheck, Terminal, XCircle } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { api, patch, post } from '../api';
import type { Device, Project } from '../types';
import { Banner, Button, Empty, Field, IconButton, Modal, Status } from '../components/ui';

interface ConnectSession {id:string;state:string;expires_at:string;connect_key?:string}

export function OverviewView({project, role, onChanged}:{project:Project;role:string;onChanged:()=>Promise<void>}) {
  const canManage = role === 'tenant_admin' || role === 'project_manager';
  const [devices,setDevices]=useState<Device[]>([]);const [connect,setConnect]=useState<ConnectSession>();const [copied,setCopied]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState('');const [editOpen,setEditOpen]=useState(false);const [lifecycle,setLifecycle]=useState<'archive'|'restore'>();
  const load=()=>api<Device[]>(`/api/bff/projects/${project.id}/devices`).then(setDevices).catch(e=>setError(e.message));
  useEffect(()=>{setConnect(undefined);setError('');load()},[project.id]);
  useEffect(()=>{if(!connect||connect.state!=='waiting_for_computer')return;const timer=window.setInterval(async()=>{try{const next=await api<ConnectSession>(`/api/bff/connect-sessions/${connect.id}`);setConnect(prev=>({...next,connect_key:prev?.connect_key}));if(next.state==='connected'){load();onChanged()}}catch{/* next interval retries */}},2000);return()=>clearInterval(timer)},[connect?.id,connect?.state]);
  const command=useMemo(()=>connect?.connect_key?`npx --yes @goodvision/contentcloud@latest init --server-url ${window.location.origin} --connect ${connect.connect_key} --target all --accept-project-config ./contentcloud-project`:'',[connect?.connect_key]);
  const createConnect=async()=>{setBusy('connect');setError('');try{setConnect(await post<ConnectSession>(`/api/bff/projects/${project.id}/connect-sessions`))}catch(e){setError(message(e,'创建失败'))}finally{setBusy('')}};
  const cancelConnect=async()=>{if(!connect)return;setBusy('cancel-connect');setError('');try{const next=await post<ConnectSession>(`/api/bff/connect-sessions/${connect.id}/cancel`);setConnect({...next,connect_key:connect.connect_key})}catch(e){setError(message(e,'取消连接失败'))}finally{setBusy('')}};
  const copy=async()=>{await navigator.clipboard.writeText(command);setCopied(true);window.setTimeout(()=>setCopied(false),1500)};
  const changeLifecycle=async()=>{if(!lifecycle)return;const action=lifecycle;setBusy(action);setError('');try{await post<Project>(`/api/bff/projects/${project.id}/${action}`,{row_version:project.row_version});setLifecycle(undefined);await onChanged()}catch(e){setError(message(e,action==='archive'?'项目归档失败':'项目恢复失败'))}finally{setBusy('')}};
  const archived=project.status==='archived';
  const headingActions=canManage?<div className="heading-actions">{!archived&&<><Button variant="secondary" onClick={()=>setEditOpen(true)}><Pencil size={15}/>编辑项目</Button><Button variant="secondary" onClick={()=>setLifecycle('archive')}><Archive size={15}/>归档</Button></>}{archived&&role==='tenant_admin'&&<Button variant="secondary" onClick={()=>setLifecycle('restore')}><RotateCcw size={15}/>恢复项目</Button>}</div>:undefined;
  return <ProjectPage project={project} kicker="项目总览" title={project.product_name} actions={headingActions}>
    {error&&<Banner kind="error" onClose={()=>setError('')}>{error}</Banner>}
    {archived&&<Banner kind="warning">项目已归档，业务数据保持只读；租户管理员恢复后才可继续写入或连接设备。</Banner>}
    <section className="overview-grid"><div className="project-facts"><header><h2>项目基线</h2><Status value={project.status}/></header><dl><div><dt>品牌</dt><dd>{project.brand_name}</dd></div><div><dt>首发渠道</dt><dd>{channelName(project.channel)}</dd></div><div><dt>阶段目标</dt><dd>{project.stage_objective||'待补充'}</dd></div><div><dt>负责人</dt><dd>{project.owner_name||'待指派'}</dd></div><div><dt>内部审核</dt><dd>{project.reviewer_name||'待指派'}</dd></div><div><dt>客户审批</dt><dd>{project.client_approver||'待指派'}</dd></div></dl></div><div className="gate-summary"><header><h2>准入状态</h2><span>Gate 0</span></header><Gate ok={devices.length>0} label="客户端运行时" detail={devices.length?`${devices.length} 台设备已授权`:'等待项目设备'}/><Gate ok={project.knowledge_ready>0} label="可信知识" detail={`${project.knowledge_ready} 条已批准`}/><Gate ok={Boolean(project.owner_name&&project.reviewer_name)} label="项目角色" detail="负责人和审核边界"/></div></section>
    <section className="section connection-section"><header className="section-header"><div><span className="section-kicker">Local Workspace</span><h2>客户端工作区</h2></div>{canManage&&<Button variant="secondary" disabled={archived||busy==='connect'||connect?.state==='waiting_for_computer'} onClick={createConnect}><Plus size={16}/>{busy==='connect'?'创建中…':'初始化电脑'}</Button>}</header>
      {connect?.connect_key&&<div className="connect-panel"><div className="connect-step"><div className="step-number">1</div><div><strong>在当前电脑运行</strong><span>连接码将在 {formatExpiry(connect.expires_at)} 失效</span></div><Status value={connect.state}/></div><div className="command-box"><Terminal size={17}/><code>{command}</code><IconButton label="复制命令" onClick={copy}>{copied?<Check size={17}/>:<Clipboard size={17}/>}</IconButton></div>{connect.state==='waiting_for_computer'&&<div className="waiting-row"><div className="waiting"><LoaderCircle size={16}/>等待客户端心跳</div><Button variant="ghost" disabled={busy==='cancel-connect'} onClick={cancelConnect}><XCircle size={15}/>{busy==='cancel-connect'?'取消中…':'取消连接'}</Button></div>}{connect.state==='canceled'&&<Banner kind="warning">连接会话已取消，当前连接码不再有效。</Banner>}</div>}
      {devices.length===0&&!connect?<Empty title="尚未初始化客户端工作区" detail={archived?'项目恢复后可初始化本地工作区。':undefined} action={canManage&&!archived?<Button onClick={createConnect}><Laptop2 size={17}/>初始化电脑</Button>:undefined}/>:<div className="device-list">{devices.map(device=><div className="device-row" key={device.id}><div className="device-icon"><Laptop2 size={18}/></div><div><strong>{device.display_name}</strong><span>{device.platform} · {device.arch} · CLI {device.daemon_version}</span></div><span className="online-dot">已绑定</span><span>{device.capabilities.length?`${device.capabilities.length} 项本地能力`:'工作区模式'}</span></div>)}</div>}
    </section>
    {editOpen&&<EditProjectModal project={project} onClose={()=>setEditOpen(false)} onSaved={async()=>{setEditOpen(false);await onChanged()}}/>}
    {lifecycle&&<Modal title={lifecycle==='archive'?'归档项目':'恢复项目'} onClose={()=>setLifecycle(undefined)}><div className="confirm-copy">{lifecycle==='archive'?<Archive size={20}/>:<RotateCcw size={20}/>}<p>{lifecycle==='archive'?'归档后项目及其业务对象进入只读状态，现有数据和审计记录都会保留。':'恢复后项目重新进入进行中状态，可以继续编辑、连接设备和创建内容。'}</p></div><div className="modal-actions"><Button variant="ghost" onClick={()=>setLifecycle(undefined)}>取消</Button><Button variant={lifecycle==='archive'?'danger':'primary'} disabled={busy===lifecycle} onClick={changeLifecycle}>{busy===lifecycle?'处理中…':lifecycle==='archive'?'确认归档':'确认恢复'}</Button></div></Modal>}
  </ProjectPage>
}

function EditProjectModal({project,onClose,onSaved}:{project:Project;onClose:()=>void;onSaved:()=>Promise<void>}) {
  const [form,setForm]=useState({brand_name:project.brand_name,product_name:project.product_name,channel:project.channel,stage_objective:project.stage_objective,owner_name:project.owner_name,reviewer_name:project.reviewer_name,client_approver:project.client_approver});
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const save=async()=>{setBusy(true);setError('');try{await patch<Project>(`/api/bff/projects/${project.id}`,{...form,row_version:project.row_version});await onSaved()}catch(e){setError(message(e,'项目保存失败'))}finally{setBusy(false)}};
  return <Modal title="编辑项目" onClose={onClose}><div className="form-grid two"><Field label="品牌"><input value={form.brand_name} onChange={e=>setForm({...form,brand_name:e.target.value})}/></Field><Field label="单品"><input value={form.product_name} onChange={e=>setForm({...form,product_name:e.target.value})}/></Field><Field label="首发渠道"><select value={form.channel} onChange={e=>setForm({...form,channel:e.target.value})}><option value="douyin">抖音</option><option value="xiaohongshu">小红书</option><option value="wechat_channels">视频号</option></select></Field><Field label="阶段目标"><input value={form.stage_objective} onChange={e=>setForm({...form,stage_objective:e.target.value})}/></Field><Field label="负责人"><input value={form.owner_name} onChange={e=>setForm({...form,owner_name:e.target.value})}/></Field><Field label="内部审核"><input value={form.reviewer_name} onChange={e=>setForm({...form,reviewer_name:e.target.value})}/></Field><Field label="客户审批"><input value={form.client_approver} onChange={e=>setForm({...form,client_approver:e.target.value})}/></Field></div>{error&&<p className="form-error">{error}</p>}<div className="modal-actions"><Button variant="ghost" onClick={onClose}>取消</Button><Button disabled={busy||!form.brand_name.trim()||!form.product_name.trim()||!form.channel} onClick={save}>{busy?'保存中…':'保存修改'}</Button></div></Modal>;
}

export function ProjectPage({project,kicker,title,actions,children}:{project:Project;kicker:string;title:string;actions?:React.ReactNode;children:React.ReactNode}) { return <div className="page"><div className="page-heading project-heading"><div><span className="eyebrow">{project.brand_name} · {kicker}</span><h1>{title}</h1><p>{project.stage_objective}</p></div>{actions}</div>{children}</div> }
function Gate({ok,label,detail}:{ok:boolean;label:string;detail:string}){return <div className={`gate ${ok?'gate-ok':''}`}><div>{ok?<ShieldCheck size={17}/>:<span/>}</div><div><strong>{label}</strong><span>{detail}</span></div>{ok?<span>通过</span>:<span>未就绪</span>}</div>}
const channelName=(v:string)=>({douyin:'抖音',xiaohongshu:'小红书',wechat_channels:'视频号'}[v]||v);
const formatExpiry=(v:string)=>new Intl.DateTimeFormat('zh-CN',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(v));
const message=(error:unknown,fallback:string)=>error instanceof Error?error.message:fallback;
