import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Check, ChevronRight, FileCheck2, GitCompareArrows, MessageSquareText, RefreshCw, ShieldCheck, X } from 'lucide-react';
import { api, post } from '../api';
import type { ApprovedSnapshot, Project, Submission, SubmissionDetails, SubmissionRevision } from '../types';
import { Banner, Button, Empty, Field, IconButton, Loading, Status } from '../components/ui';
import { ProjectPage } from './OverviewView';

export function SubmissionsView({project,role}:{project:Project;role:string}) {
  const [items,setItems]=useState<Submission[]>([]);const [snapshots,setSnapshots]=useState<ApprovedSnapshot[]>([]);const [selectedID,setSelectedID]=useState('');const [details,setDetails]=useState<SubmissionDetails>();const [revisionID,setRevisionID]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [decision,setDecision]=useState<'approve'|'changes'>('approve');const [reason,setReason]=useState('');const [pointer,setPointer]=useState('');
  const canReview=['tenant_admin','project_manager','reviewer'].includes(role);
  const load=async()=>{setLoading(true);setError('');try{const [submissions,approved]=await Promise.all([api<Submission[]>(`/api/bff/projects/${project.id}/submissions`),api<ApprovedSnapshot[]>(`/api/bff/projects/${project.id}/approved-snapshots`)]);setItems(submissions);setSnapshots(approved);setSelectedID(previous=>submissions.some(item=>item.id===previous)?previous:submissions[0]?.id||'')}catch(e){setError(e instanceof Error?e.message:'提交审核加载失败')}finally{setLoading(false)}};
  useEffect(()=>{setDetails(undefined);setSelectedID('');load()},[project.id]);
  useEffect(()=>{if(!selectedID){setDetails(undefined);return}api<SubmissionDetails>(`/api/bff/submissions/${selectedID}`).then(value=>{setDetails(value);setRevisionID(previous=>value.revisions.some(item=>item.id===previous)?previous:value.submission.current_revision_id||value.revisions[0]?.id||'')}).catch(e=>setError(e instanceof Error?e.message:'提交详情加载失败'))},[selectedID]);
  const revision=details?.revisions.find(item=>item.id===revisionID);const previous=details?.revisions.find(item=>item.revision_no===(revision?.revision_no||1)-1);const current=details?.submission.current_revision_id===revision?.id;const actionable=current&&['submitted','in_review'].includes(details?.submission.status||'');
  const disclosureCounts=useMemo(()=>countDisclosures(revision),[revision]);
  const decide=async()=>{if(!revision||!reason.trim())return;setBusy(true);setError('');try{if(decision==='approve')await post(`/api/bff/submission-revisions/${revision.id}/approve`,{reason});else await post(`/api/bff/submission-revisions/${revision.id}/request-changes`,{reason,json_pointer:pointer});setReason('');setPointer('');await load();const refreshed=await api<SubmissionDetails>(`/api/bff/submissions/${selectedID}`);setDetails(refreshed)}catch(e){setError(e instanceof Error?e.message:'审核决定失败')}finally{setBusy(false)}};
  return <ProjectPage project={project} kicker="云端治理" title="提交审核" actions={<IconButton label="刷新提交" onClick={load}><RefreshCw size={17}/></IconButton>}>
    {error&&<Banner kind="error" onClose={()=>setError('')}>{error}</Banner>}
    {loading?<div className="submission-loading"><Loading/></div>:items.length===0?<Empty title="暂无待审核提交" detail="本地客户端 publish 后会在这里形成不可变版本"/>:<>
      <div className="submission-summary"><div><FileCheck2 size={18}/><span>提交</span><strong>{items.length}</strong></div><div><MessageSquareText size={18}/><span>待处理</span><strong>{items.filter(item=>['submitted','in_review','changes_requested'].includes(item.status)).length}</strong></div><div><ShieldCheck size={18}/><span>批准快照</span><strong>{snapshots.length}</strong></div><div><AlertTriangle size={18}/><span>证据受限</span><strong>{details?.revisions.filter(item=>item.evidence_limited).length||0}</strong></div></div>
      <div className="submission-workspace">
        <section className="section submission-list"><header className="section-header"><div><span className="section-kicker">检查点</span><h2>{items.length} 个提交</h2></div></header><div>{items.map(item=><button key={item.id} className={selectedID===item.id?'active':''} onClick={()=>setSelectedID(item.id)}><span className="submission-type">{typeLabel(item.submission_type)}</span><div><strong>{typeLabel(item.submission_type)}检查点</strong><small>{formatDate(item.updated_at)} · {item.current_revision_id.slice(0,8)}</small></div><Status value={item.status}/><ChevronRight size={15}/></button>)}</div></section>
        <section className="section submission-detail">{!details||!revision?<div className="submission-loading"><Loading/></div>:<>
          <header className="section-header"><div><span className="section-kicker">不可变版本</span><h2>{typeLabel(details.submission.submission_type)} · V{revision.revision_no}</h2></div><Status value={details.submission.status}/></header>
          <div className="revision-strip">{details.revisions.map(item=><button key={item.id} className={item.id===revision.id?'active':''} onClick={()=>setRevisionID(item.id)}><span>V{item.revision_no}</span><small>{item.content_hash.slice(0,10)}</small>{item.id===details.submission.current_revision_id&&<i>当前</i>}</button>)}</div>
          <div className="revision-facts"><div><span>内容摘要</span><code>{revision.content_hash.slice(0,24)}</code></div><div><span>Schema</span><strong>{revision.schema_version}</strong></div><div><span>对象</span><strong>{revision.objects.length}</strong></div><div><span>披露</span><strong>{revision.source_disclosures.length}</strong></div></div>
          {revision.evidence_limited&&<Banner kind="error">高风险内容的证据披露不足，当前版本不能远程批准。</Banner>}
          {previous&&<div className="revision-compare"><GitCompareArrows size={16}/><div><strong>与 V{previous.revision_no} 比较</strong><span>对象 {signed(revision.objects.length-previous.objects.length)} · 披露 {signed(revision.source_disclosures.length-previous.source_disclosures.length)} · hash 已变化</span></div></div>}
          <div className="submission-tabs"><section><header><strong>审核对象</strong><span>{revision.objects.length}</span></header><div className="object-list">{revision.objects.map((object,index)=><article key={String(object.id||index)}><div><strong>{String(object.title||object.name||object.id||`对象 ${index+1}`)}</strong><span>{String(object.kind||object.deliverability||object.status||'content')}</span></div><code>{object.id?String(object.id).slice(0,12):`#${index+1}`}</code><details><summary>字段</summary><pre>{JSON.stringify(object,null,2)}</pre></details></article>)}</div></section>
            <aside><div className="disclosure-summary"><header><strong>来源披露</strong></header><dl><div><dt>仅元数据</dt><dd>{disclosureCounts.metadata_only}</dd></div><div><dt>证据包</dt><dd>{disclosureCounts.evidence_pack}</dd></div><div><dt>完整原件</dt><dd>{disclosureCounts.full_source}</dd></div></dl>{revision.source_disclosures.map(item=><div className="disclosure-row" key={item.id||item.source_ref}><span>{item.source_ref}</span><strong>{disclosureLabel(item.level)}</strong><code>{item.sha256.replace('sha256:','').slice(0,10)}</code></div>)}</div>
            <div className="feedback-list"><header><strong>审核记录</strong><span>{details.comments.filter(item=>item.subject_id===revision.id).length}</span></header>{details.comments.filter(item=>item.subject_id===revision.id).map(item=><article key={item.id}><span>{item.json_pointer||'整版'}</span><p>{item.body}</p><small>{formatDate(item.created_at)}</small></article>)}</div></aside></div>
          {canReview&&actionable&&<div className="submission-decision"><div className="decision-segment"><button className={decision==='approve'?'active':''} onClick={()=>setDecision('approve')}><Check size={15}/>批准</button><button className={decision==='changes'?'active':''} onClick={()=>setDecision('changes')}><X size={15}/>提出修改</button></div><div className="decision-fields">{decision==='changes'&&<Field label="字段位置"><input value={pointer} onChange={event=>setPointer(event.target.value)} placeholder="/0/shots/2/voiceover"/></Field>}<Field label={decision==='approve'?'整版结论':'修改要求'}><textarea value={reason} onChange={event=>setReason(event.target.value)} rows={3}/></Field><Button disabled={busy||!reason.trim()} onClick={decide}>{busy?'提交中…':decision==='approve'?'批准并生成快照':'发送修改要求'}</Button></div></div>}
        </>}</section>
      </div>
    </>}
  </ProjectPage>
}

const typeLabel=(value:string)=>({knowledge:'知识',research:'研究',strategy:'策略',brief:'Brief',script:'剧本',delivery:'交付',performance:'投放结果'}[value]||value);
const disclosureLabel=(value:string)=>({metadata_only:'仅元数据',evidence_pack:'证据包',full_source:'完整原件'}[value]||value);
const formatDate=(value:string)=>new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value));
const signed=(value:number)=>value>0?`+${value}`:`${value}`;
function countDisclosures(revision?:SubmissionRevision){const result={metadata_only:0,evidence_pack:0,full_source:0};revision?.source_disclosures.forEach(item=>result[item.level]++);return result}
