package cli

import (
	"bufio"
	"context"
	"encoding/json"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/limecloud/contentcloud/internal/apiclient"
	"github.com/limecloud/contentcloud/internal/app"
	"github.com/limecloud/contentcloud/internal/domain"
	"github.com/limecloud/contentcloud/internal/localworkspace"
)

func (r *Root) initCommand() *cobra.Command {
	var connectCode, legacyConnectCode, name, target string
	var dryRun, acceptProjectConfig bool
	cmd := &cobra.Command{
		Use:   "init [directory]",
		Args:  cobra.MaximumNArgs(1),
		Short: "Initialize a local-first ContentCloud V2 workspace",
		RunE: func(cmd *cobra.Command, args []string) error {
			directory := "."
			if len(args) == 1 {
				directory = args[0]
			}
			plan, err := localworkspace.Plan(directory, target)
			if err != nil {
				return err
			}
			if plan.State == "non_empty" {
				return workspaceConflict(plan.Conflicts)
			}
			if plan.State == "workspace" {
				status, err := localworkspace.LoadStatus(plan.Root)
				if err != nil {
					return err
				}
				return r.writeOK("init", map[string]any{"idempotent": true, "workspace": status, "daemon_enabled": false, "uploaded_files": 0})
			}
			if dryRun {
				return r.writeOK("init", map[string]any{"dry_run": true, "plan": plan, "requires_connect_code": true, "requires_project_config_acceptance": target != "none"})
			}
			code := strings.TrimSpace(connectCode)
			if code == "" {
				code = strings.TrimSpace(legacyConnectCode)
			}
			if code == "" {
				return domain.Invalid("CONNECT_KEY_REQUIRED", "--connect 必填；请先在 Web 创建项目并生成一次性 init code")
			}
			if target != "none" && !acceptProjectConfig {
				err := domain.Policy("PROJECT_CONFIG_CONFIRMATION_REQUIRED", "初始化将写入项目级 Agent Skill 和 MCP 配置", "检查 --dry-run 输出后传入 --accept-project-config；不会修改全局 Agent 配置")
				err.ExitCode = 2
				return err
			}
			cfg, result, err := r.connectDevice(cmd.Context(), code, name)
			if err != nil {
				return err
			}
			status, err := localworkspace.Initialize(localworkspace.InitOptions{
				Root:        plan.Root,
				WorkspaceID: result.WorkspaceID,
				ProjectID:   result.ProjectID,
				DeviceID:    result.Device.ID,
				ServerURL:   r.resolveServer(cfg),
				CLIVersion:  Version,
				Target:      target,
				Now:         time.Now(),
			})
			if err != nil {
				return err
			}
			report, err := localworkspace.Doctor(status.Root)
			if err != nil {
				return err
			}
			var registered domain.WorkspaceBinding
			if err := apiclient.New(r.resolveServer(cfg), result.WorkspaceToken).Dispatch(cmd.Context(), "workspace.register", map[string]any{"template_id": status.Template.TemplateID, "template_version": status.Template.TemplateVersion, "targets": status.Template.Targets}, &registered); err != nil {
				return err
			}
			return r.writeOK("init", map[string]any{
				"workspace":           status,
				"doctor":              report,
				"device":              result.Device,
				"daemon_enabled":      false,
				"uploaded_files":      0,
				"credential_store":    credentialProvider(),
				"cloud_binding":       registered,
				"next_command":        "contentcloud workspace doctor",
				"architecture_notice": "本地负责知识与内容生产，云端只负责提交、审批和治理",
			})
		},
	}
	cmd.Flags().StringVar(&connectCode, "connect", "", "one-time project init code generated by the Web application")
	cmd.Flags().StringVar(&legacyConnectCode, "connect-key", "", "compatibility alias for --connect")
	cmd.Flags().StringVar(&name, "name", "", "workspace device display name")
	cmd.Flags().StringVar(&target, "target", "all", "project Agent configuration target: codex, claude, all, or none")
	cmd.Flags().BoolVar(&acceptProjectConfig, "accept-project-config", false, "allow project-level Skill and MCP configuration files")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "show filesystem changes without consuming the init code")
	return cmd
}

func (r *Root) workspaceCommand() *cobra.Command {
	cmd := &cobra.Command{Use: "workspace", Short: "Inspect the local-first ContentCloud workspace"}
	cmd.AddCommand(
		&cobra.Command{Use: "status [directory]", Args: cobra.MaximumNArgs(1), Short: "Show binding, template, local changes, and pull state", RunE: func(cmd *cobra.Command, args []string) error {
			status, err := localworkspace.LoadStatus(optionalDirectory(args))
			if err != nil {
				return err
			}
			return r.writeOK("workspace.status", enrichWorkspaceStatus(status))
		}},
		r.workspaceDoctorCommand(),
	)
	return cmd
}

func (r *Root) workspaceDoctorCommand() *cobra.Command {
	var offline bool
	cmd := &cobra.Command{Use: "doctor [directory]", Args: cobra.MaximumNArgs(1), Short: "Check workspace structure, Skills, MCP, and cloud reachability", RunE: func(cmd *cobra.Command, args []string) error {
		report, err := localworkspace.Doctor(optionalDirectory(args))
		if err != nil {
			return err
		}
		binding, err := localworkspace.ProjectBinding(report.Root)
		if err != nil {
			return err
		}
		serverCheck := localworkspace.Check{OK: true, Required: false, Message: "云端连接检查已跳过"}
		if !offline {
			ctx, cancel := context.WithTimeout(cmd.Context(), 5*time.Second)
			defer cancel()
			err := apiclient.New(binding.ServerURL, "").Health(ctx)
			serverCheck = localworkspace.Check{OK: err == nil, Required: false, Message: defaultValue(errorStringValue(err), "云端可访问")}
		}
		report.Checks["cloud"] = serverCheck
		return r.writeOK("workspace.doctor", report)
	}}
	cmd.Flags().BoolVar(&offline, "offline", false, "skip cloud reachability check")
	return cmd
}

func (r *Root) mcpCommand() *cobra.Command {
	cmd := &cobra.Command{Use: "mcp", Short: "Run and inspect the project-local ContentCloud MCP server"}
	cmd.AddCommand(
		&cobra.Command{Use: "status [directory]", Args: cobra.MaximumNArgs(1), Short: "Show the project MCP installation state", RunE: func(cmd *cobra.Command, args []string) error {
			root, err := localworkspace.FindRoot(optionalDirectory(args))
			if err != nil {
				return err
			}
			paths := map[string]string{
				"descriptor": filepath.Join(root, ".contentcloud", "mcp", "contentcloud-local.json"),
				"codex":      filepath.Join(root, ".codex", "config.toml"),
				"claude":     filepath.Join(root, ".mcp.json"),
			}
			installed := map[string]bool{}
			for name, path := range paths {
				info, statErr := os.Stat(path)
				installed[name] = statErr == nil && !info.IsDir()
			}
			return r.writeOK("mcp.status", map[string]any{"name": "contentcloud-local", "root": root, "installed": installed, "transport": "stdio"})
		}},
		&cobra.Command{Use: "serve", Args: cobra.NoArgs, Short: "Serve project-local MCP tools over stdio", RunE: func(cmd *cobra.Command, args []string) error {
			return r.serveMCP(cmd.Context(), cmd.InOrStdin())
		}},
	)
	return cmd
}

type mcpRequest struct {
	JSONRPC string          `json:"jsonrpc"`
	ID      json.RawMessage `json:"id,omitempty"`
	Method  string          `json:"method"`
	Params  json.RawMessage `json:"params,omitempty"`
}

type mcpResponse struct {
	JSONRPC string          `json:"jsonrpc"`
	ID      json.RawMessage `json:"id,omitempty"`
	Result  any             `json:"result,omitempty"`
	Error   *mcpError       `json:"error,omitempty"`
}

type mcpError struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

func (r *Root) serveMCP(ctx context.Context, input io.Reader) error {
	scanner := bufio.NewScanner(input)
	scanner.Buffer(make([]byte, 64*1024), 2*1024*1024)
	encoder := json.NewEncoder(r.stdout)
	for scanner.Scan() {
		select {
		case <-ctx.Done():
			return nil
		default:
		}
		var request mcpRequest
		if err := json.Unmarshal(scanner.Bytes(), &request); err != nil {
			if encodeErr := encoder.Encode(mcpResponse{JSONRPC: "2.0", Error: &mcpError{Code: -32700, Message: "invalid JSON-RPC request"}}); encodeErr != nil {
				return encodeErr
			}
			continue
		}
		if request.Method == "notifications/initialized" {
			continue
		}
		response := r.handleMCPRequest(ctx, request)
		if err := encoder.Encode(response); err != nil {
			return err
		}
	}
	return scanner.Err()
}

func (r *Root) handleMCPRequest(ctx context.Context, request mcpRequest) mcpResponse {
	response := mcpResponse{JSONRPC: "2.0", ID: request.ID}
	switch request.Method {
	case "initialize":
		response.Result = map[string]any{
			"protocolVersion": "2025-03-26",
			"capabilities":    map[string]any{"tools": map[string]any{"listChanged": false}},
			"serverInfo":      map[string]string{"name": "contentcloud-local", "version": Version},
		}
	case "ping":
		response.Result = map[string]any{}
	case "tools/list":
		response.Result = map[string]any{"tools": mcpTools()}
	case "tools/call":
		result, err := r.callLocalMCPTool(ctx, request.Params)
		if err != nil {
			response.Result = mcpToolError(err)
		} else {
			response.Result = result
		}
	default:
		response.Error = &mcpError{Code: -32601, Message: "method not found"}
	}
	return response
}

func mcpTools() []map[string]any {
	directory := map[string]any{
		"type":                 "object",
		"properties":           map[string]any{"directory": map[string]any{"type": "string", "description": "Workspace path; defaults to current directory"}},
		"additionalProperties": false,
	}
	preflight := map[string]any{
		"type": "object",
		"properties": map[string]any{
			"directory":        map[string]any{"type": "string", "description": "Workspace path; defaults to current directory"},
			"submission_type":  map[string]any{"type": "string", "enum": []string{"knowledge", "research", "strategy", "brief", "script", "delivery", "performance"}},
			"files":            map[string]any{"type": "array", "items": map[string]any{"type": "string"}, "description": "Workspace-relative JSON checkpoint files; defaults to the type output directory"},
			"disclosures_file": map[string]any{"type": "string", "description": "Workspace-relative source disclosure JSON file"},
			"message":          map[string]any{"type": "string", "description": "Review note included in the computed hash"},
		},
		"required":             []string{"submission_type"},
		"additionalProperties": false,
	}
	submissionStatus := map[string]any{
		"type": "object",
		"properties": map[string]any{
			"directory":     map[string]any{"type": "string", "description": "Workspace path; defaults to current directory"},
			"submission_id": map[string]any{"type": "string"},
		},
		"required":             []string{"submission_id"},
		"additionalProperties": false,
	}
	snapshots := map[string]any{
		"type": "object",
		"properties": map[string]any{
			"directory":       map[string]any{"type": "string", "description": "Workspace path; defaults to current directory"},
			"submission_type": map[string]any{"type": "string", "enum": []string{"knowledge", "research", "strategy", "brief", "script", "delivery", "performance"}},
		},
		"additionalProperties": false,
	}
	sourceRegister := map[string]any{
		"type": "object",
		"properties": map[string]any{
			"directory":    map[string]any{"type": "string", "description": "Workspace path; defaults to current directory"},
			"file":         map[string]any{"type": "string", "description": "Source file path"},
			"id":           map[string]any{"type": "string", "description": "Stable source ID"},
			"title":        map[string]any{"type": "string"},
			"source_kind":  map[string]any{"type": "string"},
			"storage_mode": map[string]any{"type": "string", "enum": []string{"copy", "reference"}},
		},
		"required":             []string{"file"},
		"additionalProperties": false,
	}
	sourceID := map[string]any{
		"type": "object",
		"properties": map[string]any{
			"directory": map[string]any{"type": "string", "description": "Workspace path; defaults to current directory"},
			"source_id": map[string]any{"type": "string"},
		},
		"required":             []string{"source_id"},
		"additionalProperties": false,
	}
	localRunInit := map[string]any{
		"type": "object",
		"properties": map[string]any{
			"directory":   map[string]any{"type": "string", "description": "Workspace path; defaults to current directory"},
			"run_id":      map[string]any{"type": "string"},
			"intent":      map[string]any{"type": "string", "enum": []string{"ingest", "query", "content"}},
			"source_refs": map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
			"with_ingest": map[string]any{"type": "boolean"},
		},
		"required":             []string{"intent"},
		"additionalProperties": false,
	}
	localRunShow := map[string]any{
		"type": "object",
		"properties": map[string]any{
			"directory": map[string]any{"type": "string", "description": "Workspace path; defaults to current directory"},
			"run_id":    map[string]any{"type": "string", "description": "Defaults to current run"},
		},
		"additionalProperties": false,
	}
	knowledgeImport := map[string]any{
		"type": "object",
		"properties": map[string]any{
			"directory":  map[string]any{"type": "string", "description": "Workspace path; defaults to current directory"},
			"file":       map[string]any{"type": "string", "description": "Workspace-relative knowledge-candidates/1.0 file"},
			"origin_run": map[string]any{"type": "string"},
		},
		"required":             []string{"file"},
		"additionalProperties": false,
	}
	knowledgeQuery := map[string]any{
		"type": "object",
		"properties": map[string]any{
			"directory": map[string]any{"type": "string", "description": "Workspace path; defaults to current directory"},
			"channel":   map[string]any{"type": "string"},
			"at":        map[string]any{"type": "string", "format": "date-time"},
		},
		"additionalProperties": false,
	}
	knowledgePack := map[string]any{
		"type": "object",
		"properties": map[string]any{
			"directory": map[string]any{"type": "string", "description": "Workspace path; defaults to current directory"},
			"pack_id":   map[string]any{"type": "string"},
			"name":      map[string]any{"type": "string"},
		},
		"additionalProperties": false,
	}
	localFile := map[string]any{
		"type": "object",
		"properties": map[string]any{
			"directory": map[string]any{"type": "string", "description": "Workspace path; defaults to current directory"},
			"file":      map[string]any{"type": "string", "description": "Workspace-relative JSON file"},
		},
		"required":             []string{"file"},
		"additionalProperties": false,
	}
	creativeBatchInit := map[string]any{
		"type": "object",
		"properties": map[string]any{
			"directory":             map[string]any{"type": "string", "description": "Workspace path; defaults to current directory"},
			"brief_id":              map[string]any{"type": "string"},
			"directions_file":       map[string]any{"type": "string"},
			"requested_count":       map[string]any{"type": "integer", "minimum": 1, "maximum": 10},
			"variant_dimension":     map[string]any{"type": "string", "enum": []string{"hook", "audience", "scenario", "visualization", "cta", "duration"}},
			"controlled_dimensions": map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
			"batch_id":              map[string]any{"type": "string"},
		},
		"required":             []string{"directions_file", "requested_count", "variant_dimension"},
		"additionalProperties": false,
	}
	scriptLint := map[string]any{
		"type": "object",
		"properties": map[string]any{
			"directory":  map[string]any{"type": "string", "description": "Workspace path; defaults to current directory"},
			"file":       map[string]any{"type": "string", "description": "Workspace-relative ScriptPackage V2 file"},
			"batch_file": map[string]any{"type": "string", "description": "Workspace-relative batch.json"},
		},
		"required":             []string{"file"},
		"additionalProperties": false,
	}
	creativeBatchFiles := map[string]any{
		"type": "object",
		"properties": map[string]any{
			"directory":    map[string]any{"type": "string", "description": "Workspace path; defaults to current directory"},
			"batch_file":   map[string]any{"type": "string"},
			"script_files": map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
		},
		"required":             []string{"batch_file", "script_files"},
		"additionalProperties": false,
	}
	scriptDiff := map[string]any{
		"type": "object",
		"properties": map[string]any{
			"directory":      map[string]any{"type": "string", "description": "Workspace path; defaults to current directory"},
			"baseline_file":  map[string]any{"type": "string"},
			"candidate_file": map[string]any{"type": "string"},
			"allowed_paths":  map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
		},
		"required":             []string{"baseline_file", "candidate_file", "allowed_paths"},
		"additionalProperties": false,
	}
	scriptExport := map[string]any{
		"type": "object",
		"properties": map[string]any{
			"directory":        map[string]any{"type": "string", "description": "Workspace path; defaults to current directory"},
			"script_id":        map[string]any{"type": "string"},
			"output_directory": map[string]any{"type": "string"},
		},
		"required":             []string{"script_id"},
		"additionalProperties": false,
	}
	return []map[string]any{
		{"name": "workspace_status", "description": "Read local workspace binding, template and synchronization state without contacting the cloud", "inputSchema": directory},
		{"name": "workspace_doctor", "description": "Validate local workspace structure, managed files, Skills and MCP configuration", "inputSchema": directory},
		{"name": "source_register", "description": "Register an immutable local customer source without uploading it", "inputSchema": sourceRegister},
		{"name": "source_list", "description": "List local source registry records without contacting the cloud", "inputSchema": directory},
		{"name": "source_ingest", "description": "Parse a registered source into exact local evidence spans", "inputSchema": sourceID},
		{"name": "source_verify", "description": "Verify local source hashes and MIME types", "inputSchema": directory},
		{"name": "local_run_init", "description": "Initialize a resumable local ingest, query, or content workflow", "inputSchema": localRunInit},
		{"name": "local_run_show", "description": "Read a LocalRunContext without cloud communication", "inputSchema": localRunShow},
		{"name": "knowledge_import_candidates", "description": "Import knowledge-candidates/1.0 after exact evidence verification", "inputSchema": knowledgeImport},
		{"name": "knowledge_lint", "description": "Run deterministic local knowledge governance checks", "inputSchema": directory},
		{"name": "knowledge_query", "description": "Classify knowledge as eligible, blocked, or informational", "inputSchema": knowledgeQuery},
		{"name": "knowledge_diagnose", "description": "Produce the 15-dimension customer material diagnosis", "inputSchema": knowledgeQuery},
		{"name": "knowledge_pack", "description": "Build a seven-layer knowledge review pack and evidence disclosures", "inputSchema": knowledgePack},
		{"name": "brief_lint", "description": "Validate a local Brief V2 against current eligible knowledge", "inputSchema": localFile},
		{"name": "creative_batch_init", "description": "Freeze approved Brief and Knowledge snapshots into a local CreativeBatch", "inputSchema": creativeBatchInit},
		{"name": "script_lint", "description": "Validate one ScriptPackage V2 against its frozen local batch context", "inputSchema": scriptLint},
		{"name": "creative_batch_lint", "description": "Validate every ScriptPackage candidate in a CreativeBatch", "inputSchema": creativeBatchFiles},
		{"name": "creative_batch_finalize", "description": "Finalize a validated local CreativeBatch without creating a cloud TaskRun", "inputSchema": creativeBatchFiles},
		{"name": "script_diff", "description": "Detect undeclared JSON Pointer drift in a script revision or variant", "inputSchema": scriptDiff},
		{"name": "script_export", "description": "Export a pulled approved ScriptPackage V2 as JSON, Markdown, and XLSX", "inputSchema": scriptExport},
		{"name": "publish_preflight", "description": "Validate a local immutable checkpoint and show exactly what would be review-visible without publishing", "inputSchema": preflight},
		{"name": "submission_status", "description": "Read the current cloud governance status for a workspace submission", "inputSchema": submissionStatus},
		{"name": "review_feedback_list", "description": "Read cloud review feedback for this workspace without changing local business files", "inputSchema": directory},
		{"name": "approved_snapshot_list", "description": "List immutable approved snapshots available to this workspace", "inputSchema": snapshots},
	}
}

func (r *Root) callLocalMCPTool(ctx context.Context, raw json.RawMessage) (map[string]any, error) {
	var params struct {
		Name      string `json:"name"`
		Arguments struct {
			Directory            string   `json:"directory"`
			File                 string   `json:"file"`
			ID                   string   `json:"id"`
			Title                string   `json:"title"`
			SourceKind           string   `json:"source_kind"`
			StorageMode          string   `json:"storage_mode"`
			SourceID             string   `json:"source_id"`
			RunID                string   `json:"run_id"`
			Intent               string   `json:"intent"`
			SourceRefs           []string `json:"source_refs"`
			WithIngest           bool     `json:"with_ingest"`
			OriginRun            string   `json:"origin_run"`
			Channel              string   `json:"channel"`
			At                   string   `json:"at"`
			PackID               string   `json:"pack_id"`
			Name                 string   `json:"name"`
			BriefID              string   `json:"brief_id"`
			DirectionsFile       string   `json:"directions_file"`
			RequestedCount       int      `json:"requested_count"`
			VariantDimension     string   `json:"variant_dimension"`
			ControlledDimensions []string `json:"controlled_dimensions"`
			BatchID              string   `json:"batch_id"`
			BatchFile            string   `json:"batch_file"`
			ScriptFiles          []string `json:"script_files"`
			BaselineFile         string   `json:"baseline_file"`
			CandidateFile        string   `json:"candidate_file"`
			AllowedPaths         []string `json:"allowed_paths"`
			ScriptID             string   `json:"script_id"`
			OutputDirectory      string   `json:"output_directory"`
			SubmissionType       string   `json:"submission_type"`
			SubmissionID         string   `json:"submission_id"`
			Files                []string `json:"files"`
			DisclosuresFile      string   `json:"disclosures_file"`
			Message              string   `json:"message"`
		} `json:"arguments"`
	}
	if err := json.Unmarshal(raw, &params); err != nil {
		return nil, domain.Invalid("MCP_PARAMS_INVALID", "MCP tool 参数无效")
	}
	var value any
	var err error
	switch params.Name {
	case "workspace_status":
		value, err = localworkspace.LoadStatus(params.Arguments.Directory)
	case "workspace_doctor":
		value, err = localworkspace.Doctor(params.Arguments.Directory)
	case "source_register":
		if strings.TrimSpace(params.Arguments.File) == "" {
			return nil, domain.Invalid("LOCAL_SOURCE_FILE_REQUIRED", "file 必填")
		}
		value, err = localworkspace.RegisterLocalSource(localworkspace.RegisterLocalSourceOptions{Root: params.Arguments.Directory, File: params.Arguments.File, ID: params.Arguments.ID, Title: params.Arguments.Title, SourceKind: params.Arguments.SourceKind, StorageMode: params.Arguments.StorageMode, Now: time.Now()})
	case "source_list":
		var sources []localworkspace.LocalSource
		sources, err = localworkspace.LocalSources(params.Arguments.Directory)
		value = map[string]any{"count": len(sources), "sources": sources}
	case "source_ingest":
		if strings.TrimSpace(params.Arguments.SourceID) == "" {
			return nil, domain.Invalid("LOCAL_SOURCE_ID_REQUIRED", "source_id 必填")
		}
		value, err = localworkspace.IngestLocalSource(params.Arguments.Directory, params.Arguments.SourceID, time.Now())
	case "source_verify":
		var report localworkspace.SourceVerification
		report, err = localworkspace.VerifyLocalSources(params.Arguments.Directory)
		value = report
		if err == nil && !report.Valid {
			err = domain.Invalid("LOCAL_SOURCE_VERIFY_FAILED", "本地来源完整性校验失败")
		}
	case "local_run_init":
		value, err = localworkspace.InitLocalRun(localworkspace.InitLocalRunOptions{Root: params.Arguments.Directory, RunID: params.Arguments.RunID, Intent: params.Arguments.Intent, SourceRefs: params.Arguments.SourceRefs, WithIngest: params.Arguments.WithIngest, Now: time.Now()})
	case "local_run_show":
		value, err = localworkspace.ShowLocalRun(params.Arguments.Directory, params.Arguments.RunID)
	case "knowledge_import_candidates":
		if strings.TrimSpace(params.Arguments.File) == "" {
			return nil, domain.Invalid("LOCAL_FILE_REQUIRED", "file 必填")
		}
		value, err = localworkspace.ImportKnowledgeCandidates(localworkspace.ImportKnowledgeOptions{Root: params.Arguments.Directory, PackageFile: params.Arguments.File, OriginRunID: params.Arguments.OriginRun, Now: time.Now()})
	case "knowledge_lint":
		var report localworkspace.KnowledgeLintReport
		report, err = localworkspace.LintKnowledge(params.Arguments.Directory)
		value = report
		if err == nil && !report.Valid {
			lintErr := domain.Invalid("KNOWLEDGE_LINT_FAILED", "知识库确定性校验失败")
			lintErr.Details = report
			err = lintErr
		}
	case "knowledge_query", "knowledge_diagnose":
		var at time.Time
		at, err = parseLocalQueryTime(params.Arguments.At)
		if err != nil {
			break
		}
		if params.Name == "knowledge_query" {
			value, err = localworkspace.QueryKnowledge(localworkspace.QueryKnowledgeOptions{Root: params.Arguments.Directory, Channel: params.Arguments.Channel, At: at})
		} else {
			value, err = localworkspace.DiagnoseKnowledge(params.Arguments.Directory, params.Arguments.Channel, at)
		}
	case "knowledge_pack":
		value, err = localworkspace.PackKnowledge(localworkspace.PackKnowledgeOptions{Root: params.Arguments.Directory, PackID: params.Arguments.PackID, Name: params.Arguments.Name, Now: time.Now()})
	case "brief_lint":
		var report localworkspace.KnowledgeLintReport
		var brief localworkspace.LocalBrief
		report, brief, err = localworkspace.LintBrief(params.Arguments.Directory, params.Arguments.File)
		value = map[string]any{"brief": brief, "report": report}
		if err == nil && !report.Valid {
			lintErr := domain.Invalid("BRIEF_LINT_FAILED", "Brief V2 确定性校验失败")
			lintErr.Details = report
			err = lintErr
		}
	case "creative_batch_init":
		value, err = localworkspace.CreateCreativeBatch(localworkspace.CreateCreativeBatchOptions{Root: params.Arguments.Directory, BriefID: params.Arguments.BriefID, DirectionsFile: params.Arguments.DirectionsFile, RequestedCount: params.Arguments.RequestedCount, VariantDimension: params.Arguments.VariantDimension, ControlledDimensions: params.Arguments.ControlledDimensions, BatchID: params.Arguments.BatchID, Now: time.Now()})
	case "script_lint":
		var report localworkspace.ScriptLintReport
		report, _, err = localworkspace.LintScriptPackage(params.Arguments.Directory, params.Arguments.File, params.Arguments.BatchFile)
		value = report
		if err == nil && !report.Valid {
			lintErr := domain.Invalid("SCRIPT_PACKAGE_LINT_FAILED", "ScriptPackage V2 确定性校验失败")
			lintErr.Details = report
			err = lintErr
		}
	case "creative_batch_lint":
		var report localworkspace.ScriptBatchLintReport
		report, err = localworkspace.LintCreativeBatch(params.Arguments.Directory, params.Arguments.BatchFile, params.Arguments.ScriptFiles)
		value = report
		if err == nil && !report.Valid {
			lintErr := domain.Invalid("CREATIVE_BATCH_LINT_FAILED", "CreativeBatch 确定性校验失败")
			lintErr.Details = report
			err = lintErr
		}
	case "creative_batch_finalize":
		value, err = localworkspace.FinalizeCreativeBatch(params.Arguments.Directory, params.Arguments.BatchFile, params.Arguments.ScriptFiles, time.Now())
	case "script_diff":
		var diff localworkspace.ScriptDiff
		diff, err = localworkspace.DiffScriptPackages(params.Arguments.Directory, params.Arguments.BaselineFile, params.Arguments.CandidateFile, params.Arguments.AllowedPaths)
		value = diff
		if err == nil && !diff.Valid {
			diffErr := domain.Invalid("SCRIPT_REVISION_DRIFT", "修订包含未声明字段变化")
			diffErr.Details = diff
			err = diffErr
		}
	case "script_export":
		value, err = localworkspace.ExportApprovedScript(params.Arguments.Directory, params.Arguments.ScriptID, params.Arguments.OutputDirectory, time.Now())
	case "publish_preflight":
		if !validSubmissionType(params.Arguments.SubmissionType) {
			return nil, domain.Invalid("SUBMISSION_TYPE_INVALID", "submission_type 无效")
		}
		root, findErr := localworkspace.FindRoot(params.Arguments.Directory)
		if findErr != nil {
			return nil, findErr
		}
		_, preflight, buildErr := buildPublishCheckpoint(publishBuildOptions{Root: root, SubmissionType: params.Arguments.SubmissionType, Files: params.Arguments.Files, DisclosuresFile: params.Arguments.DisclosuresFile, Message: params.Arguments.Message})
		value, err = map[string]any{"preflight": preflight, "cloud_write": false, "business_files_modified": false}, buildErr
	case "submission_status":
		if strings.TrimSpace(params.Arguments.SubmissionID) == "" {
			return nil, domain.Invalid("SUBMISSION_ID_REQUIRED", "submission_id 必填")
		}
		_, client, _, clientErr := r.workspaceClient(params.Arguments.Directory)
		if clientErr != nil {
			return nil, clientErr
		}
		var details app.SubmissionDetails
		err = client.Dispatch(ctx, "submission.workspace-show", map[string]any{"id": params.Arguments.SubmissionID}, &details)
		value = map[string]any{"submission_id": details.Submission.ID, "status": details.Submission.Status, "current_revision_id": details.Submission.CurrentRevisionID, "revision_count": len(details.Revisions)}
	case "review_feedback_list":
		_, client, _, clientErr := r.workspaceClient(params.Arguments.Directory)
		if clientErr != nil {
			return nil, clientErr
		}
		var feedback []domain.ReviewFeedbackBundle
		err = client.Dispatch(ctx, "feedback.workspace-list", map[string]any{}, &feedback)
		value = map[string]any{"count": len(feedback), "feedback": feedback, "business_files_modified": false}
	case "approved_snapshot_list":
		if params.Arguments.SubmissionType != "" && !validSubmissionType(params.Arguments.SubmissionType) {
			return nil, domain.Invalid("SUBMISSION_TYPE_INVALID", "submission_type 无效")
		}
		_, client, _, clientErr := r.workspaceClient(params.Arguments.Directory)
		if clientErr != nil {
			return nil, clientErr
		}
		var snapshots []domain.ApprovedSnapshot
		err = client.Dispatch(ctx, "snapshot.workspace-list", map[string]any{"submission_type": params.Arguments.SubmissionType}, &snapshots)
		value = map[string]any{"count": len(snapshots), "snapshots": snapshots}
	default:
		return nil, domain.NotFound("MCP tool")
	}
	if err != nil {
		return nil, err
	}
	body, err := json.Marshal(value)
	if err != nil {
		return nil, err
	}
	return map[string]any{"content": []map[string]string{{"type": "text", "text": string(body)}}, "structuredContent": value, "isError": false}, nil
}

func validSubmissionType(value string) bool {
	switch value {
	case "knowledge", "research", "strategy", "brief", "script", "delivery", "performance":
		return true
	default:
		return false
	}
}

func mcpToolError(err error) map[string]any {
	return map[string]any{"content": []map[string]string{{"type": "text", "text": err.Error()}}, "isError": true}
}

func optionalDirectory(args []string) string {
	if len(args) == 1 {
		return args[0]
	}
	return ""
}

func workspaceConflict(paths []string) error {
	shown := paths
	if len(shown) > 8 {
		shown = shown[:8]
	}
	err := domain.Conflict("WORKSPACE_DIRECTORY_NOT_EMPTY", "目标目录非空且不是 ContentCloud 工作区")
	err.Hint = "请选择空目录，或先确认并整理冲突文件：" + strings.Join(shown, ", ")
	err.Details = map[string]any{"conflicts": paths}
	return err
}

func enrichWorkspaceStatus(status localworkspace.Status) map[string]any {
	return map[string]any{
		"workspace": status,
		"agents": map[string]any{
			"codex":  executableAvailable("codex"),
			"claude": executableAvailable("claude"),
		},
		"disclosure_policy": map[string]any{"default": "evidence_pack", "raw_upload": false},
		"automation":        map[string]any{"enabled": status.AutomationEnabled, "required_for_local_work": false},
	}
}

func executableAvailable(name string) bool {
	_, err := exec.LookPath(name)
	return err == nil
}

func errorStringValue(err error) string {
	if err == nil {
		return ""
	}
	return err.Error()
}
